### ISSUE TITLE
SSH question for a multi-container load operation (docker-compose).

### ISSUE THREAD

**Issue by Axxon** [ypereirareis/docker-satis#21]
Hello and first thanks for share that work.
Here my case, i installed gitlab with docker from the repository sameersbn/docker-gitlab, it's work well. I added satis container parameters on the given compose file. But i can't understand how does ssh work in your scenario, in the doc it's say that "The container needs to know the ssh key you added in your private repo." so we speak about a Public key, so id_rsa.pub is'nt it ? 
Other thing, i don't know if with docker 1.9.1 with consideration of the gitlab compose file and the use of "links" parameter i need to add another one in satis section even if i put in PRIVATE_REPO_DOMAIN_LIST env the IP address of my gitlab container.

**Comment by ypereirareis** [comment]
HI !

Sorry for the late response....
Do you still have troubles ?

**Comment by Axxon** [comment]
Hello thanks for coming back ! Yes i stop to try (cause i've a lot others things to do), but i really need to plug satis to gitlab. Did you understand my problem ?

**Comment by jdoubleu** [comment]
Okay,

I had nearly the same setup like you and I got it to work.

As I understand you, you want to manage your repositories with gitlab and publish/release them to satis?

**My solution:**
My GitLab is running inside a container, such as satis.
Both are connected to a bridge network (see [documentation](https://docs.docker.com/engine/userguide/networking/dockernetworks/).

I've linked the gitlab container to my satis container, giving the alias of the public domain so I can use the domain when adding new packages to the satis repository.
Ex:

```
  links:
     - gitlab-container:git.example.com
```

Your GitLab instance listens on port 22 (inside the container) for incoming ssh connections. May this port is exposed differently to the docker host you still need to use 22 (or leave it blank because it's the default port) because the containers are connected.

> But i can't understand how does ssh work in your scenario, in the doc it's say that "The container needs to know the ssh key you added in your private repo." so we speak about a Public key, so id_rsa.pub is'nt it ?

As you might now, you can pull/clone git repositories through ssh. In GitLab you can add deployment keys so that the owner of the key can only deploy the repository.
I created a ssh key and linked it, like described in the [README.md](https://github.com/ypereirareis/docker-satis/blob/master/README.md) to the satis container. Then I added the public sign (e.g. `id_rsa.pub`) to GitLab and enabled it for my project.

After that I can add a repository to satis:

```
  ...
  repositories: [
    { "type": "git", "url": "ssh://git@git.example.com/vendor/repo" },
    ...
   ],
 ...
```

When satis or git inside your container are trying to clone the repository they auth with your added ssh key.

In the installation script the `PRIVATE_REPO_DOMAIN_LIST` option is needed to add your host to the know_hosts. Otherwise you would be prompted to add it to the known_hosts first time you clone from this host and this would break the container.

**Note:**
If you want to run satis and gitlab from different `docker-compose.yml` files use `external_links` instead of `links`!

**Comment by ypereirareis** [comment]
You need to use gitlab Hook to publish and build new repos to satis automatically
Satis needs to have an ssh key authorized on your repos.
